# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-06-30 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
